---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: devops-secret
  namespace: default
spec:
  encryptedData:
    DBPASSWORD: AgDOIyB9YmT3HiSeNAeTVB8ZWMHIk5ZDTRq6AppsAqe+2dMD31mF0hIMaAjVvSCHtLzmFDkjDOOITRA6E2M3Ml2KXlvA6l8/ZfcDpWZh0+mvOP0X0afOFvYtjlfF43XMzZzUCb4jDZYcgwU26HpsW+XZCfRh8gwaKa8vMxu6b3ZselJF/5dE2SVRlbZTih8JwcPITXBiQ3PmwooJUFXLz7lR0TBftHU63b4vNM8nHCQ/C16lg3OiV2f5fngXwF7cu7NNccLA/Wk2Gh2lUVlmf5R2eNeFFzFEGS7oHilslK7eDRPYxgJL/95Qus2qQko0B2T0ncUlXLTvWsXKY6mrQv8pJMlMPdMXyw2YbJ97Hwmkn6fuBZahc1kV/+Qtb8Ps0zPd9EdKbUfsCxDKCF5NZI3dA8uhXW9IX/zoylcrvA0hwHQRUC9F6hRzZkcj116EM7TQL9cyLc6JScP/lMcbJBSyfMkZQ5CMkTxv4huyk4GWWgn+zmN6+QdIL77ukzB1bOxtXyziwznCBSG9a8qFCu5m7CzX137uoQEaCemjyRaPHFwZ/8exC7PPr5gCT2MRUK12CpTVWk1i21/t3rH5C/Lr/SwiadCbMT3Oz/onBUcGjHrchCOGdjM/ll8bYSRy3j0KWt2cJ2I9eqy9MLVeIFlZE6ajA1271jk/arolT98EcYa6BNr8QhHcWfgkSlMr0qTua8TFbQ==
    DBUSERNAME: AgBZ0CKevWKt+VEePeJLm6uZCopTBiN7q7bV8C7IheMHB7YxW2qV93c9bR0UIKpbcxuCGMTNtR2ZeAWo4E7v2D5LHPTLsfZSOvMf3VIqDj72zFMxmULugzQ8I9wAEHD/wv5XkSe1vlQanRLqzXRdY0gzHn/3sNjr4hDkzRvWzdFZPllZW5ohE+TsESle3yQbmzUoK8qhV/k1GIuEOR+jPL2R+dWmR8oR+X437dqGDE6SU+6DzHF4BMHTsbZ1WugibAmDlZ6TBfb2No6OTa/HuLdPr6PWL5A/KGha6LbJEICZHRWQvfWtS5RDbR5psga0ynV7x/NorHJdwptRomsboFVxGFQ4urdr9IHJ5XR9wv7XA2dki+mo1kUALTYTUBNk6l0kq3bw/bZWoJnKPskmEotl2mMnVxHM0MV9h4+tGHl94d13AsebNtnG8s2c+qcMRusbBsVqZYLPQFfAVYriZItruAc5QZFE8xPMjZ83lmxue6LJP/78uLjWmN9wER1BTQvdFS7KBQF+eMAopbsIx+B6W6d98NtTm+Vb98Sk9/3m11RYgqX2SczmFZrvubR48BjtvyppRgDhspzaacKh7LDPGsuG1tW4jzBHe6X9d11juzlaiPuDlYRgbCCQEnoKlAsY+RltVP+7KERwddY3VKICodrkg9LhpWOjveiZwk3fCycEbnBynuQ5DIoDNAm4kynp8UbXvA==
  template:
    metadata:
      creationTimestamp: null
      name: secret-name
      namespace: default
